name: Batch Build ROCm Wheels

on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Comma-seperated version tags of llama-cpp-python to build'
        default: 'v0.1.83,v0.1.82,v0.1.81,v0.1.80'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  define_matrix:
    name: Define Workflow Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    defaults:
      run:
        shell: pwsh
    env:
      PCKGVERS: ${{ inputs.versions }}
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Define Job Output
        id: set-matrix
        run: |
          $versions = $env:PCKGVERS.Split(',').Trim()
          $versions.foreach({if ([version]$_.TrimStart('v') -lt [version]'0.1.80') {Throw "$_ does not support ROCm!"}})
          $x = ConvertTo-Json $versions -Compress
          Write-Output ('matrix=' + $x) >> $env:GITHUB_OUTPUT
          
  run_workflows:
    name: Build ${{ matrix.version }} Wheels
    needs: define_matrix
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJSON(needs.define_matrix.outputs.matrix) }}
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ matrix.version }}
