name: Build Wheels test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.83'
        default: 'v0.1.83'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.83'
        default: 'v0.1.83'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build_wheels:
    name: ${{ matrix.os }} ${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        pyver: ["3.10", "3.8", "3.9", "3.11"]
        arch: ["x86_64","arm64"]
    env:
      CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}
      PCKGVER: ${{ inputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: ${{ inputs.version }}
          submodules: 'recursive'
          
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install Dependencies
        run: |
          python -m pip install build wheel cmake
          
      - name: Build Wheel
        run: |
          export CMAKE_ARGS="-DCMAKE_SYSTEM_PROCESSOR=$CMAKE_OSX_ARCHITECTURES -DLLAMA_METAL=on"
          NPY_BLAS_ORDER='accelerate' NPY_LAPACK_ORDER='accelerate' FORCE_CMAKE=1 VERBOSE=1 python -m build --wheel
        
      - uses: actions/upload-artifact@v3
        with:
          name: macos-wheels
          path: ./dist/*.whl
