name: Build Wheels for New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.11'
        default: 'v0.2.11'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  run_main:
    name: Build ${{ inputs.version }} CUDA Wheels
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ inputs.version }}
      cpu: '0'
      
  run_ooba:
    name: Build ${{ inputs.version }} CUDA Wheels for Text Generation Webui
    needs: run_main
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      
  run_cpu:
    name: Build CPU-only Wheels
    needs: run_ooba
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      
  run_macos:
    name: Build MacOS Metal Wheels
    needs: run_cpu
    uses: ./.github/workflows/build-wheels-macos.yml
    with:
      version: ${{ inputs.version }}
      
  run_rocm:
    name: Build ROCm Wheels
    needs: run_macos
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ inputs.version }}
