name: Build Wheels test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.6'
        default: 'v0.2.6'
        required: true
        type: string

jobs:
  build_wheels_main:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        pyver: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: ${{ inputs.version }}
          submodules: 'recursive'
          
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install Dependencies
        run: |
          python -m pip install build wheel cmake
          
      - name: Build Wheel
        run: |
          export CMAKE_ARGS="-DLLAMA_METAL=on"
          export SDKROOT="macosx14.0"
          export MACOSX_DEPLOYMENT_TARGET="10.13"
          [[ "$CMAKE_OSX_ARCHITECTURES" = "x86_64" ]] && export CMAKE_ARGS="-DLLAMA_AVX=off -DLLAMA_AVX2=off -DLLAMA_FMA=off -DLLAMA_F16C=off -DLLAMA_METAL=on" && export ARCHFLAGS="-arch x86_64"
          [[ "$CMAKE_OSX_ARCHITECTURES" = "arm64" ]] && export ARCHFLAGS="-arch arm64"
          CMAKE_ARGS="-DLLAMA_METAL=on" VERBOSE=1 python -m build --wheel
        
      - uses: actions/upload-artifact@v3
        if: steps.upload-release.outcome == 'failure'
        with:
          name: macos-wheels
          path: ./dist/*.whl
